---
- ip: '127.0.1.2'
  rack: eu-west-1a
  dc: eu-west-1
  token: 0
  dnode_port: 8101
  client_port: 8102
  local_connections: 0
  remote_connections: 0
  req_conf:
    read_consistency: 'DC_SAFE_QUORUM'
    write_consistency: 'DC_SAFE_QUORUM'
- ip: '127.0.1.3'
  rack: eu-west-1b
  dc: eu-west-1
  token: 0
  dnode_port: 8101
  client_port: 8102
  local_connections: 0
  remote_connections: 0
  req_conf:
    read_consistency: 'DC_SAFE_QUORUM'
    write_consistency: 'DC_SAFE_QUORUM'
- ip: '127.0.1.4'
  rack: eu-west-1c
  dc: eu-west-1
  token: 0
  dnode_port: 8101
  client_port: 8102
  local_connections: 0
  remote_connections: 0
  req_conf:
    read_consistency: 'DC_SAFE_QUORUM'
    write_consistency: 'DC_SAFE_QUORUM'
